BullMarket/Models/Corretagem.cs
using System;

namespace BullMarket.Web.Models
{
    public class Corretagem
    {
        public int Id { get; set; }
        public DateTime DataCompra { get; set; } = DateTime.Today;
        public CorretoraEnum Corretora { get; set; }
        public int Quantidade { get; set; }
        public decimal ValorCompra { get; set; }
        public decimal ValorAgora { get; set; }

        public decimal Diferenca
        {
            get
            {
                return ValorAgora - ValorCompra;
            }
        }

        public decimal PorcentagemRetorno
        {
            get
            {
                return ((ValorAgora * 100) / ValorCompra) / 100;
            }
        }

        public decimal ValorTotalCompra
        {
            get
            {
                return ValorCompra * Quantidade;
            }
        }

        public decimal ValorTotalAgora
        {
            get
            {
                return ValorAgora * Quantidade;
            }
        }

        public decimal LucroReal
        {
            get
            {
                return ValorTotalAgora - ValorTotalCompra;
            }
        }

        public decimal Custos { get; set; }
        public StatusEnum Status { get; set; }

        public int AcaoId { get; set; }
        public Empresa Acao { get; set; }
    }
}

BullMarket/Models/CorretoraEnum.cs
namespace BullMarket.Web.Models
{
    public enum CorretoraEnum
    {
        XP = 1,
        Clear = 2
    }
}

BullMarket/Models/Empresa.cs
namespace BullMarket.Web.Models
{
    public class Empresa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
        public string Ramo { get; set; }
        public string Link { get; set; }
    }
}

BullMarket/Models/StatusEnum.cs
namespace BullMarket.Web.Models
{
    public enum StatusEnum
    {
        Desejo = 1,
        Carteira = 2,
        Vendido = 3
    }
}

BullMarket/Controllers/CorretagensController.cs
using BullMarket.Web.Models;
using BullMarket.Web.Repository;
using HtmlAgilityPack;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BullMarket.Web.Controllers
{
    public class CorretagensController : Controller
    {
        private readonly BullMarketContext _context;

        public CorretagensController(BullMarketContext context) => _context = context;

        public async Task<IActionResult> Index()
        {
            HtmlWeb website = new HtmlWeb
            {
                AutoDetectEncoding = false,
                OverrideEncoding = Encoding.Default
            };

            List<Corretagem> corretagens = await _context.Corretagens.Include(c => c.Acao).Where(p => p.Status != StatusEnum.Vendido).ToListAsync();

            foreach (var item in corretagens)
            {
                HtmlDocument Doc = website.Load(item.Acao.Link);
                var valor = Doc.DocumentNode.Descendants().Where(p => p.Id == "last_last").FirstOrDefault().InnerText;

                if (!decimal.TryParse(valor, out decimal valorAtual))
                    continue;

                item.ValorAgora = valorAtual;
                await Update(item);
            }

            return View();
        }

        public async Task<IActionResult> CarregaCreate()
        {
            ViewBag.AcaoId = new SelectList(await _context.Empresas.ToListAsync(), "Id", "Codigo");
            return PartialView("_Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Corretagem corretagem)
        {
            if (!ModelState.IsValid)
                return Json(new { Mensagem = "Formuario invalido" });

            _context.Add(corretagem);
            await _context.SaveChangesAsync();

            return Json(new { Mensagem = "Sucesso" });
        }

        public async Task<IActionResult> CarregaUpdate(int? id)
        {
            if (id == null)
                return Json(new { Mensagem = "Falha" });

            var corretagem = await _context.Corretagens.FindAsync(id);
            if (corretagem == null)
                return Json(new { Mensagem = "Falha" });

            return PartialView("_Update", corretagem);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Corretagem corretagem)
        {
            if (!ModelState.IsValid)
                return Json(new { Mensagem = "Formuario invalido" });

            _context.Update(corretagem);
            await _context.SaveChangesAsync();

            return Json(new { Mensagem = "Sucesso" });
        }

        public async Task<IActionResult> Lista() => PartialView("_Lista", await _context.Corretagens.Include(p => p.Acao).ToListAsync());
    }
}

BullMarket/Controllers/EmpresasController.cs
using BullMarket.Web.Models;
using BullMarket.Web.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace BullMarket.Web.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly BullMarketContext _context;

        public EmpresasController(BullMarketContext context) => _context = context;

        public IActionResult Index() => View();

        public IActionResult CarregaCreate() => PartialView("_Create");

        [HttpPost]
        public async Task<IActionResult> Create(Empresa empresa)
        {
            if (!ModelState.IsValid)
                return Json(new { Mensagem = "Formuario invalido" });

            _context.Add(empresa);
            await _context.SaveChangesAsync();

            return Json(new { Mensagem = "Sucesso" });
        }

        public async Task<IActionResult> CarregaUpdate(int? id)
        {
            if (id == null)
                return Json(new { Mensagem = "Falha" });

            var empresa = await _context.Empresas.FindAsync(id);
            if (empresa == null)
                return Json(new { Mensagem = "Falha" });

            return PartialView("_Update", empresa);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Empresa empresa)
        {
            if (id != empresa.Id)
                return Json(new { Mensagem = "Falha" });

            if (!ModelState.IsValid)
                return Json(new { Mensagem = "Formulario invalido" });

            _context.Update(empresa);
            await _context.SaveChangesAsync();

            return Json(new { Mensagem = "Sucesso" });
        }

        public async Task<IActionResult> Lista() => PartialView("_Lista", await _context.Empresas.ToListAsync());
    }
}

BullMarket/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BullMarket.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BullMarket/Views/Corretagens/Index.cshtml
@{
    ViewData["Title"] = "Corretagem";
}

<h2>Corretagem</h2>

<p>
    <button type="button" onclick="CarregaCreate()" class="btn btn-primary">Adicionar corretagem</button>
</p>

<div id="lista"></div>

<div class="modal" id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div id="corpoModal"></div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            lista();
        });

        function lista() {
            $("#lista").load("/Corretagens/Lista");
        }

        function CarregaCreate() {
            $("#corpoModal").load("/Corretagens/CarregaCreate");
            $("#modal").modal('show')
        }

        function Create() {
            var objeto = $("#form").serialize()
            $.post("/Corretagens/Create", objeto, function (data) {
                lista();
                $("#modal").modal('hide')
                $("#corpoModal").html("")
                alert(data.mensagem)
            });
        }

        function CarregaUpdate(id) {
            $("#corpoModal").load("/Corretagens/CarregaUpdate/" + id);
            $("#modal").modal('show')
        }

        function Update() {
            var objeto = $("#form").serialize()
            $.post("/Corretagens/Update", objeto, function (data) {
                lista();
                $("#modal").modal('hide')
                $("#corpoModal").html("")
                alert(data.mensagem)
            });
        }
    </script>
}

BullMarket/Views/Corretagens/_Create.cshtml
@model BullMarket.Web.Models.Corretagem

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Nova corretagem</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form id="form">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="DataCompra" class="control-label"></label>
                    <input asp-for="DataCompra" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="Corretora" class="control-label"></label>
                    <select asp-for="Corretora" class="form-control" asp-items="Html.GetEnumSelectList<BullMarket.Web.Models.CorretoraEnum>()">
                        <option>Selecione</option>
                    </select>
                </div>

                <div class="col-md-6">
                    <label asp-for="AcaoId" class="control-label"></label>
                    <select asp-for="AcaoId" class="form-control" asp-items="ViewBag.AcaoId">
                        <option>Selecione</option>
                    </select>
                </div>
                <div class="col-md-6">
                    <label asp-for="Quantidade" class="control-label"></label>
                    <input asp-for="Quantidade" class="form-control" />
                </div>

                <div class="col-md-6">
                    <label asp-for="ValorCompra" class="control-label"></label>
                    <input asp-for="ValorCompra" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="ValorAgora" class="control-label"></label>
                    <input asp-for="ValorAgora" class="form-control" />
                </div>

                <div class="col-md-6">
                    <label asp-for="Custos" class="control-label"></label>
                    <input asp-for="Custos" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<BullMarket.Web.Models.StatusEnum>()">
                        <option>Selecione</option>
                    </select>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" onclick="Create()" class="btn btn-primary">Salvar</button>
    </div>
</div>

BullMarket/Views/Corretagens/_Lista.cshtml
@model IEnumerable<BullMarket.Web.Models.Corretagem>

<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th>
                Ação
            </th>
            <th>
                Corretora
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                Qtde
            </th>
            <th>
                Compra
            </th>
            <th>
                Atual
            </th>
            <th>
                Total Compra
            </th>
            <th>
                Total atual
            </th>
            <th>
                Diferença
            </th>
            <th>
                Retorno
            </th>
            <th>
                Lucro
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Custos)
            </th>
            <th>Editar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.DataCompra.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Acao.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Corretora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorCompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorAgora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorTotalCompra)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValorTotalAgora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Diferenca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PorcentagemRetorno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LucroReal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Custos)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BullMarket/Views/Corretagens/_Update.cshtml
@model BullMarket.Web.Models.Corretagem

@{
    ViewData["Title"] = "Edit";
}

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Atualizar corretagem</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form id="form">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="DataCompra" class="control-label"></label>
                    <input asp-for="DataCompra" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="Corretora" class="control-label"></label>
                    <select asp-for="Corretora" class="form-control"></select>
                </div>

                <div class="col-md-6">
                    <label asp-for="AcaoId" class="control-label"></label>
                    <select asp-for="AcaoId" class="form-control" asp-items="ViewBag.AcaoId"></select>
                </div>
                <div class="col-md-6">
                    <label asp-for="Quantidade" class="control-label"></label>
                    <input asp-for="Quantidade" class="form-control" />
                </div>

                <div class="col-md-6">
                    <label asp-for="ValorCompra" class="control-label"></label>
                    <input asp-for="ValorCompra" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="ValorAgora" class="control-label"></label>
                    <input asp-for="ValorAgora" class="form-control" />
                </div>

                <div class="col-md-6">
                    <label asp-for="Custos" class="control-label"></label>
                    <input asp-for="Custos" class="form-control" />
                </div>
                <div class="col-md-6">
                    <label asp-for="Status" class="control-label"></label>
                    <select asp-for="Status" class="form-control"></select>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" onclick="Create()" class="btn btn-primary">Salvar</button>
    </div>
</div>

BullMarket/Views/Empresas/Index.cshtml
@{
    ViewData["Title"] = "Empresas";
}

<h2>Empresas</h2>

<p>
    <button type="button" onclick="CarregaCreate()" class="btn btn-primary">Adicionar empresa</button>
</p>

<div id="lista"></div>


<div class="modal" id="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div id="corpoModal"></div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            lista();
        });

        function lista() {
            $("#lista").load("/Empresas/Lista");
        }

        function CarregaCreate() {
            $("#corpoModal").load("/Empresas/CarregaCreate");
            $("#modal").modal('show')
        }

        function Create() {
            var objeto = $("#form").serialize()
            $.post("/Empresas/Create", objeto, function (data) {
                lista();
                $("#modal").modal('hide')
                $("#corpoModal").html("")
                alert(data.mensagem)
            });
        }

        function CarregaUpdate(id) {
            $("#corpoModal").load("/Empresas/CarregaUpdate/" + id);
            $("#modal").modal('show')
        }

        function Update() {
            var objeto = $("#form").serialize()
            $.post("/Empresas/Update", objeto, function (data) {
                lista();
                $("#modal").modal('hide')
                $("#corpoModal").html("")
                alert(data.mensagem)
            });
        }
    </script>
}

BullMarket/Views/Empresas/_Create.cshtml
@model BullMarket.Web.Models.Empresa

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Nova empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <form id="form">
                    <div class="form-group col-md-12">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Codigo" class="control-label"></label>
                        <input asp-for="Codigo" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Ramo" class="control-label"></label>
                        <input asp-for="Ramo" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Link" class="control-label"></label>
                        <input asp-for="Link" class="form-control" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" onclick="Create()" class="btn btn-primary">Salvar</button>
    </div>
</div>

BullMarket/Views/Empresas/_Lista.cshtml
@model IEnumerable<BullMarket.Web.Models.Empresa>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ramo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>Editar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ramo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Link)
                </td>
                <td>
                    <a href="#" onclick="CarregaUpdate(@item.Id)">Editar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

BullMarket/Views/Empresas/_Update.cshtml
@model BullMarket.Web.Models.Empresa

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Atualizar empresa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <form id="form">
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group col-md-12">
                        <label asp-for="Nome" class="control-label"></label>
                        <input asp-for="Nome" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Codigo" class="control-label"></label>
                        <input asp-for="Codigo" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Ramo" class="control-label"></label>
                        <input asp-for="Ramo" class="form-control" />
                    </div>
                    <div class="form-group col-md-12">
                        <label asp-for="Link" class="control-label"></label>
                        <input asp-for="Link" class="form-control" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" onclick="Update()" class="btn btn-primary">Salvar</button>
    </div>
</div>

BullMarket/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

BullMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BullMarket</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BullMarket</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Corretagens" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empresas" asp-action="Index">Empresas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - BullMarket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>